name: CI/CD for Vite + Spring Boot + GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: taskdb
          POSTGRES_USER: taskuser
          POSTGRES_PASSWORD: chip24112001
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Java for Spring Boot
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      # 3. Build Spring Boot backend
      - name: Build Spring Boot backend
        run: |
          cd backend/demo
          mvn clean install -DskipTests

      # 4. Setup Node.js for Vite frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2' # ✅ Node >= 20.19+ để tương thích Vite v7

      # 5. Install and Build Vite frontend
      - name: Build Vite frontend
        run: |
          cd frontend
          npm ci
          npm run build

      # 6. Deploy frontend to GitHub Pages
      - name: Deploy Vite to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
