name: CI/CD for React + Spring Boot + GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: taskdb
          POSTGRES_USER: taskuser
          POSTGRES_PASSWORD: chip24112001
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup Java for backend
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Build backend
    - name: Build Spring Boot backend
      run: |
        cd backend/demo
        mvn clean install -DskipTests

    # 4. Setup Node.js for frontend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 5. Cache npm deps (optional)
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-npm-cache
        restore-keys: |
          ${{ runner.os }}-npm-

    # 6. Install and deploy React frontend
    - name: Install and Deploy React frontend to GitHub Pages
      run: |
        cd frontend
        npm ci
        npm run deploy
      env:
        CI: false
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}